### ISSUE TITLE
If ADMIN_PASSWORD is omitted, "connect failed" exception is thrown

### ISSUE THREAD

**Issue by vadimtar** [mongodb/support-tools#34]
mongo HOST:PORT/admin -u ADMIN_USER -p ADMIN_PASSWORD --quiet --norc getMongoData.js > getMongoData.log
The shell is not prompting for the password, If ADMIN_PASSWORD is omitted.

**Comment by niccottrell** [comment]
I think this may have been a problem with the version of Mongo shell being used, and is not an issue with this script.
